Specific_Static_Folder/urls.py
from django.contrib import admin
from django.urls import path,include
import animals,fruits

urlpatterns = [
    path('admin/', admin.site.urls),
    path('animals/',include('animals.urls')),
    path('fruits/',include('fruits.urls')),
]

animals/urls.py
from animals.views import *
from django.urls import path

app_name='animals'

urlpatterns=[
    path('cow/',cow,name='cow'),
    path('dog/',dog,name='dog'),
    path('cat/',cat,name='cat'),
]

fruits/urls.py
from fruits.views import *
from django.urls import path

app_name='fruits'

urlpatterns=[
    path('apple/',apple,name='apple'),
    path('grapes/',grapes,name='grapes'),
    path('banana/',banana,name='banana'),
]

animals/models.py
from django.db import models

# Create your models here.

fruits/models.py
from django.db import models

# Create your models here.

animals/views.py
from django.shortcuts import render

# Create your views here.
def dog(request):
    return render(request,'dog.html')

def cow(request):
    return render(request,'cow.html')

def cat(request):
    return render(request,'cat.html')

fruits/views.py
from django.shortcuts import render

# Create your views here.

def grapes(request):
    return render(request,'grapes.html')


def apple(request):
    return render(request,'apple.html')

def banana(request):
    return render(request,'banana.html')

templates/apple.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>🍎🍎!..APPLE..!🍎🍎</h1>
        <img src="{% static 'images/apple.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'fruits:banana' %}"><h1>🍌</h1></a>
        <a href="{% url 'fruits:grapes' %}"><h1>🍇</h1></a>
    </center>
</body>
</html>

templates/banana.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>🍌🍌!..BANANA..!🍌🍌</h1>
        <img src="{% static 'images/banana.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'fruits:apple' %}"><h1>🍎</h1></a>
        <a href="{% url 'fruits:grapes' %}"><h1>🍇</h1></a>
    </center>
</body>
</html>

templates/cat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>🐱🐱!..CAT..!🐱🐱</h1>
        <img src="{% static 'images/cat.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'animals:dog' %}"><h1>🐶</h1></a>
        <a href="{% url 'animals:cow' %}"><h1>🐮</h1></a>
    </center>
</body>
</html>

templates/cow.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>🐮🐮!..COW..!🐮🐮</h1>
        <img src="{% static 'images/cow.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'animals:dog' %}"><h1>🐶</h1></a>
        <a href="{% url 'animals:cat' %}"><h1>🐱</h1></a>
    </center>
</body>
</html>

templates/dog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>🐶🐶!..DOG..!🐶🐶</h1>
        <img src="{% static 'images/dog.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'animals:cat' %}"><h1>🐱</h1></a>
        <a href="{% url 'animals:cow' %}"><h1>🐮</h1></a>
    </center>
</body>
</html>

templates/grapes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">

</head>
<body>
    <center>
        <h1>🍇🍇!..GRAPES..!🍇🍇</h1>
        <img src="{% static 'images/grapes.jpg' %}" alt="not found" width="500px" height="500px" >
        <a href="{% url 'fruits:apple' %}"><h1>🍎</h1></a>
        <a href="{% url 'fruits:banana' %}"><h1>🍌</h1></a>
    </center>
</body>
</html>